// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fntflosgiofqbotdgxkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudGZsb3NnaW9mcWJvdGRneGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDE3MTAsImV4cCI6MjA1OTkxNzcxMH0.PoDd5v5OH3KQt90qGixygAi5R6qMdxSQu-oXUgDtQis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);